### ISSUE TITLE
Guruhga yangi qo'shilganlar bilan salomlashish va qoidalarga rozilik berish funksionali

### ISSUE THREAD

**Issue by vodiylik** [Linuxiston/tg-admin-helper#2]
Guruhga yangi qo'shilganlar bilan salomlashish va qoidalarga rozilik berish funksionalini qo'shish kerak,
Guruhga yangi qo'shilganlardan yozish huquqini olib qo'yib, botga maxsus link orqali o'tib qoidalarga rozilik bildirish tugmasini bosgachgina yozish imkoniyatini qo'shish kerak.

**Comment by Erkinbek** [comment]
yaxshi fikr, vaqt orttirganimda yozib qo'yaman

**Comment by vodiylik** [comment]
Shu shu qolib ketdimi?)

**Comment by Erkinbek** [comment]
> Shu shu qolib ketdimi?)

Ha, bugun dam olish kuni pochtamga kelgan notifikatsiyalarga qarab chiqayotgan edim, ko'zim tushib qoldi bunga ))

**Comment by vodiylik** [comment]
> > Shu shu qolib ketdimi?)
> 
> Ha, bugun dam olish kuni pochtamga kelgan notifikatsiyalarga qarab chiqayotgan edim, ko'zim tushib qoldi bunga ))

Tushunarli ))
